---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx
  namespace: default
spec:
  interval: 1m0s
  url:  https://helm.nginx.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: default
spec:
  interval: 1m0s
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: default
      version: "0.17.1"
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
